_target_: pytorch_lightning.Trainer
accelerator: auto
max_epochs: 1  # Single epoch for quick training and comparison
gradient_clip_val: 1.0
enable_progress_bar: true
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  log_model: true
defaults:
  - callbacks: default
