# Training configuration with cache benchmark
# This extends the base train.yaml and adds cache benchmark configuration

defaults:
  - train  # Inherit from train.yaml

# Cache benchmark configuration (optional)
# These parameters control the cache performance benchmark after training
# Reduced defaults for faster benchmark (can be overridden via command line)
cache_benchmark:
  num_samples: 5  # Number of samples for benchmark (reduced for speed)
  num_diffusion_steps: 5  # Number of diffusion steps (reduced for speed)
  cache_kwargs: {}  # Cache configuration (e.g., {"K": 5, "tau_0": 0.1})
  use_fresca: false  # Whether to test with FreSca
  fresca_kwargs: {}  # FreSca configuration if use_fresca=true
  # Example FreSca config:
  # fresca_kwargs:
  #   fresca_low_scale: 1.0
  #   fresca_high_scale: 1.5
  #   fresca_cutoff_ratio: 0.5
  #   fresca_cutoff_strategy: "energy"

